SOEN490-SportsApp/SportsApp

ClientApp/.eslintrc.json, ClientApp/app/_layout.tsx, ClientApp/app/index.tsx, ClientApp/package-lock.json, ClientApp/package.json, ClientApp/tsconfig.json
GH-99: [feat] Added esLint to clientApp
=> GH-99: [feat] Added esLint to clientApp

README.md
include frontend readme redirect
=> Update main README.md 

ClientApp/__tests__/api/axiosInstance.test.ts, ClientApp/__tests__/profile.test.tsx, ClientApp/api/axiosInstance.ts, ClientApp/app/(tabs)/_layout.tsx, ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/(tabs)/profile/index.tsx, ClientApp/app/auth/login.tsx, ClientApp/app/auth/registerAccount.tsx, ClientApp/utils/api/endpoints.tsx
- Integrated the API to complete the login functionality and allow users to use their credentials and enter the app.
- Used Axios instance and AsyncStorage to manage and store the access and refresh tokens.
After further investigation, we noticed the lack of security that AsyncStorage presents. We have decided to change this technology by expo secure store in the future (redux is also a candidate). This will make our authorization and authentication system more reliable and secure.
=> GH-29: [feat] Add login api

Microservices/user-service/src/main/java/app/sportahub/userservice/client/KeycloakApiClient.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/user/keycloak/KeycloakRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/GlobalExceptionHandler.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/InvalidCredentialsException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/repository/UserRepository.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/auth/AuthServiceImpl.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
This PR fixes two main issues in the registration and login flow:
1. **Account Activation**: Ensures newly registered accounts are activated by default, allowing users to log in immediately after registration.
2. **Error Handling**: Improves error handling in login to display descriptive messages from Keycloak, making issues like invalid credentials clearer for users.
- Set `enabled` to `true` by default in registration requests.
- Enhanced error response handling to include detailed Keycloak error messages.
- Updated `InvalidCredentialsException` and exception handling in the `GlobalExceptionHandler`.
=> GH-156 Fix Account Activation and Improve Error Handling

.gitignore, ClientApp/__tests__/auth/login.test.tsx, ClientApp/app/auth/login.tsx, ClientApp/app/auth/registerAccount.tsx, ClientApp/components/AuthenticationDivider.tsx, ClientApp/components/ConfirmButton.tsx, ClientApp/utils/constants/colors.ts, ClientApp/utils/helpers/uiScaler.ts
Linked Issue: #158 
- Centralized helper functions for ui scaling and responsivness.
- Centralized app colors and themes
- Fix login page responsivness
- Fix register account page responsivness
=> Bugfix/issue-158/non responsive UI inaccessible features

ClientApp/__tests__/api/axiosInstance.test.ts, ClientApp/__tests__/auth/login.test.tsx, ClientApp/api/axiosInstance.ts, ClientApp/app/(tabs)/_layout.tsx, ClientApp/app/_layout.tsx, ClientApp/app/auth/login.tsx, ClientApp/app/auth/registerAccount.tsx, ClientApp/utils/api/errorHandlers.ts, ClientApp/utils/context/AuthContext.tsx
- Allows users to authenticate with an identifier (e.g., email or username) and password in `login` function in `AuthContext` called from `login` component.
- Stores the received access and refresh tokens securely using `AsyncStorage` (to be encrypted in future PR). Since SecureStorage can't handle tokens of size 2048.
- Updates the userID and isAuthenticated context state to reflect successful login across the application.
- Resets logoutRequested to false to ensure a fresh session.
- initiate the access token refresh handled in function `scheduleTokenRefresh`
- Clears access and refresh tokens from `AsyncStorage`.
- Resets the `userID` and `isAuthenticated` states to ensure the user is logged out.
- Redirects the user to the login screen and resets the navigation stack (had some bugs …
=> Feature/issue #161/persist tokens and user information

Microservices/user-service/src/main/java/app/sportahub/userservice/controller/auth/AuthController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/user/ProfileRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/user/SportLevelRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/ProfileResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/SportLevelResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/UserResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/mapper/user/ProfileMapper.java, Microservices/user-service/src/main/java/app/sportahub/userservice/mapper/user/UserMapper.java, Microservices/user-service/src/main/java/app/sportahub/userservice/model/user/Profile.java, Microservices/user-service/src/main/java/app/sportahub/userservice/model/user/SportLevel.java, Microservices/user-service/src/main/java/app/sportahub/userservice/model/user/User.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/auth/AuthService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/auth/AuthServiceImpl.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/main/resources/application.properties, Microservices/user-service/src/test/java/app/sportahub/userservice/UserServiceApplicationTests.java, Microservices/user-service/src/test/java/app/sportahub/userservice/response/user/UserResponseTest.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
This PR introduces enhancements to the management of preferred sports in user profiles by incorporating a new `SportLevel` structure. The changes allow each sport to have an associated name and ranking, providing a more detailed representation of users' sports preferences. Additionally, the PR includes refactoring to improve maintainability and standardize data transformations using mappers.
1. **Controller Updates**
- Refactored return types in `AuthController` and `UserController` to directly utilize mappers for improved separation of concerns.
- Adjusted method summaries and descriptions for better clarity in Swagger documentation.
2. **DTO Additions and Updates**
- Introduced `SportLevelRequest` and `SportLevelResponse` DTOs to represent sports preferences with levels.
- Updated …
=> GH-164: [refactor] Enhance Preferred Sports Management with Sport Levels in User Profiles

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/event--template.md
New issue template for opening bugs
=> Update issue templates

ClientApp/app/auth/registerAccount.tsx
The user can now show/hide his confirm password input and verify that it matches his password input when clicking the eye icon on the right side of the input field.
=> GH-167: [fix] Confirm password UI binding fix

Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/auth/TokenResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/mapper/user/ProfileMapper.java, Microservices/user-service/src/main/java/app/sportahub/userservice/mapper/user/UserMapper.java, Microservices/user-service/src/main/java/app/sportahub/userservice/model/user/Preferences.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/auth/AuthServiceImpl.java, Microservices/user-service/src/main/java/app/sportahub/userservice/utils/JwtUtils.java, Microservices/user-service/src/main/resources/keycloak-themes/sporta/email/html/template.ftl, Microservices/user-service/src/main/resources/keycloak-themes/sporta/email/messages/messages_en.properties, Microservices/user-service/src/main/resources/keycloak-themes/sporta/email/theme.properties, Microservices/user-service/src/test/java/app/sportahub/userservice/controller/AuthControllerTest.java
This PR focuses on improving email verification and user authentication workflows while enhancing code maintainability. Key changes include sending verification emails upon successful registration, updating the user login response to include email verification status, and adding tests to validate these updates. Additionally, object mapper configurations have been adjusted for to fix issues where mappers would not behave properly, and constructors were added to models for the mappers' use.
- Added functionality in `AuthServiceImpl` to send a verification email to users upon successful registration.
- Introduced logging to confirm successful email dispatch.
- Updated `TokenResponse` to include an `emailVerified` field.
- Modified `AuthServiceImpl` to parse the `email_verified` claim from …
=> GH-152: [feat] Add email verification on register

Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/mapper/event/EventMapper.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
This PR introduces two new endpoints in the `event-service` to enable updating event details:  
- **PUT (`/events/{eventId}`):** Allows a full replacement of an event's details.  
- **PATCH (`/events/{eventId}`):** Enables partial updates to specific fields of an event.  
Both endpoints include validation, authentication, and authorization mechanisms to ensure data integrity and security. Comprehensive unit and integration tests were written to verify correctness and edge cases. Swagger documentation was updated to provide clear usage instructions for developers.  
---
- **Purpose:** Fully replace the existing event object with the data provided in the request body.  
- **Implementation Details:**  
- Added the `putEvent` method in `EventController`.  
- Developed service-layer logic to: …
=> GH-77: [feat] Add update for events

Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
- Created the delete event endpoint
- Created unit tests associated with endpoint
=> GH-81: [feat] delete event

Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/request/EventRequest.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/response/EventResponse.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/model/event/Event.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
Added a LocalTime startTime field to events
=> [refactor] Added a required LocalTime startTime field to events

ClientApp/__tests__/auth/resetPassword.test.tsx, ClientApp/app/_layout.tsx, ClientApp/app/auth/login.tsx, ClientApp/app/auth/resetPassword.tsx, ClientApp/services/authService.ts, ClientApp/services/axiosInstance.ts, ClientApp/utils/api/endpoints.tsx, ClientApp/utils/helpers/uiScaler.ts
The goal of this PR is to implement the forgot password functionality for when a user forgets their password and wishes to change it via the beginning interface.
=> GH-33: [feature] Create forget password functionality

ClientApp/__tests__/auth/login.test.tsx, ClientApp/__tests__/auth/registerAccount.test.tsx, ClientApp/__tests__/auth/registerProfile.test.tsx, ClientApp/__tests__/services/authService.test.ts, ClientApp/app/auth/login.tsx, ClientApp/app/auth/registerAccount.tsx, ClientApp/babel.config.js, ClientApp/components/RegisterProfile/RegisterProfileSports.tsx, ClientApp/jest.setup.ts
- Login.test.tsx
- registerProfile.test.tx
- authService.test
- registerAccount.test.tsx
=> GH249: [test] Increase the test coverage for frontend files

Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
Removed an unnecessary failing test and renamed other tests to follow the convention established.
=> GH-0: [fix] Removed unnecessary failing test

ClientApp/__tests__/services/tokenService.test.ts, ClientApp/__tests__/state/user/api.test.ts, ClientApp/__tests__/state/user/userSlice.test.ts, ClientApp/__tests__/utils/api/errorHandlers.test.ts, ClientApp/__tests__/utils/api/profileApiClient.test.ts, ClientApp/__tests__/utils/mappers/apiMappers.test.ts, ClientApp/services/tokenService.ts
- tokenService.test.ts
- api.test.ts
- userSlice.test.ts
- errorHandlers.test.ts
- profileApiClient.test.ts
- apiMappers.test.ts
=> Task/issue 249/increase test coverage

.github/workflows/build-deploy-microservices.yaml
This PR introduces a new GitHub Actions workflow to dynamically identify and build only the changed microservices and publish their Docker images to the GitHub Container Registry (GHCR). 
1. **Determine Changed Services**:
- Uses `git diff` to identify changes in the `Microservices` directory.
- Generates a JSON list of affected services.
2. **Build and Deploy Pipeline**:
- Iterates over the identified services.
- Builds and pushes corresponding Docker images to GHCR with the tag `latest`.
3. **Workflow Enhancements**:
- Ensures only necessary services are processed, improving efficiency.
- Includes debugging steps for better visibility during execution.
=> GH-253: [ci] Update CI Workflow for Dynamic Microservice Builds and Deployment

ClientApp/app/(tabs)/_layout.tsx, ClientApp/app/(tabs)/chats/index.tsx, ClientApp/components/Home Page/TopBar.tsx
Now the tab bar creates a better user experience. Also it has been refactored to hold these routes in this respective order :
Home - Create - Chats - Profile
=> GH-261: [fix] Fix Tab Bar and Routes

ClientApp/app/(tabs)/home/index.tsx, ClientApp/app/_layout.tsx, ClientApp/components/Event/EventListProfilePage.tsx
Now the last event in the activity section of profile is displayed as expected.
=> GH-256: [fix] Last event display profile

ClientApp/__tests__/createEvent.test.tsx, ClientApp/__tests__/services/eventService.test.ts, ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/(tabs)/home/index.tsx, ClientApp/app/events/_layout.tsx, ClientApp/components/Event/EventCard.tsx, ClientApp/components/Event/EventsListHomePage.tsx, ClientApp/services/eventService.ts, ClientApp/utils/api/endpoints.tsx
Modifications:
- improve test coverage for eventService and createEvent.
- api implementation for getting all events on home page.
- api implementation for deleting an event from an event page.
- bug fix when creating an event.
=> GH-249: [feat] Improve Testing and Add Event API

ClientApp/__tests__/services/authService.test.ts, ClientApp/__tests__/utils/api/errorHandlers.test.ts, ClientApp/app/auth/login.tsx, ClientApp/services/authService.ts, ClientApp/services/axiosInstance.ts, ClientApp/utils/api/errorHandlers.ts
- Fixed the issue where users encountered an unclear 'refresh token not found' error message on incorrect password.
- Added user-friendly error handling for invalid credentials.
- Improved alert messages and logging for better UX and debugging.
=> GH-237: [fix] Handle wrong password error gracefully

.gitignore, Microservices/event-service/src/main/java/app/sportahub/eventservice/config/WebConfig.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/converter/EventSortingFieldConverter.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/converter/SortDirectionConverter.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/enums/EventSortingField.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/enums/SortDirection.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/InvalidEventSortingFieldException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/InvalidSortingDirectionException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/repository/EventRepository.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/EventServiceApplicationTests.java, Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/PublicProfileResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/mapper/user/PublicProfileMapper.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserSearchTest.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
This PR is related to issue #44 . 
It is also important to note, that for user activity history it is the same as what is required for issue #228. 
- implemented endpoint `GET user-service/user/{id}/profile`  to retrieve user profile details (name, email, user profile)
- example response
```json
{
"username": "joe",
"profile": {
"firstName": "joe",
"lastName": "doe",
"dateOfBirth": "2005-09-09",
"gender": "Male",
"postalCode": "A1B2C3",
"phoneNumber": "123-456-7890",
"sportsOfPreference": [
{
"name": "Soccer",
"ranking": "Advanced"
},
{
"name": "Tennis",
"ranking": "Beginner"
},
{
"name": "Cycling",
"ranking": "Intermediate"
}
],
"ranking": "Test Ranking"
}
}
```
- implemented endpoint `GET event-service/event/participant/{userId}` to retrieve `pages` of events the given user has …
=> Feature/issue 44/view other user profiles

ClientApp/__tests__/event/EventCard.test.tsx, ClientApp/__tests__/event/SkillTag.test.tsx, ClientApp/__tests__/home page/Feed.test.tsx, ClientApp/__tests__/home page/TopBar.test.tsx, ClientApp/__tests__/services/axiosInstance.test.ts, ClientApp/app/(tabs)/create/index.tsx, ClientApp/components/Event/EventCard.tsx, ClientApp/components/Event/EventsListHomePage.tsx, ClientApp/components/Home Page/Feed.tsx, ClientApp/components/Home Page/TopBar.tsx, ClientApp/services/axiosInstance.ts
for #249 
wrote tests for: 
EventCard.ts
SkillTag.ts
Feed.ts
TopBar.ts
relative updates of the files to ensure tests have high coverage and they pass
=> GH-249: [fix] updated tests files to increase coverage of frontend

ClientApp/__tests__/home page/TopBar.test.tsx, ClientApp/app/(tabs)/_layout.tsx, ClientApp/app/(tabs)/home/_layout.tsx, ClientApp/app/(tabs)/home/index.tsx, ClientApp/app/(tabs)/home/searchPage.tsx, ClientApp/app/auth/login.tsx, ClientApp/components/Helper Components/CustomTabMenu.tsx, ClientApp/components/Helper Components/FriendCard.tsx, ClientApp/components/Home Page/TopBar.tsx, ClientApp/services/userService.ts, ClientApp/utils/api/endpoints.tsx
The goal of this pr is to add a search for user functionality. Now users can accomplish the following:
- access search bar from home page
- Search for users
- Get shown if a user is not found
- Mock a friend request to a user from the search section
- return to home page
UI:
=> GH-247:[feat] Search bar with search for user by name

README.md
Simply added the release 2 presentation
=> [feat] Add Release 2 Video to the README

ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/(tabs)/profile/index.tsx, ClientApp/components/Helper Components/FriendCard.tsx
- Fix the cutoff time format being sent to the backend upon event creation.
- Minor improvements in UI to Profile page and friend card upon search
=> GH-280: [fix] Fix event creation cutoff time and minor UI improvements

Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java
Event creator is now added automatically to participants
=> [refactor] add creator to event participants

ClientApp/__tests__/auth/registerAccount.test.tsx, ClientApp/app/(tabs)/profile/index.tsx, ClientApp/app/_layout.tsx, ClientApp/app/editProfile/index.tsx, ClientApp/app/editProfile/sportsSkills.tsx, ClientApp/components/RegisterProfile/RegisterProfileSports.tsx, ClientApp/package.json, ClientApp/state/user/actions.ts, ClientApp/state/user/userSlice.ts, ClientApp/utils/api/endpoints.tsx, ClientApp/utils/api/profileApiClient.ts
-Fixed icon consistency between profile and selection pages
-Updated skill level 
-Adjusted badge size & spacing for a cleaner UI
Added a confirmation page after selecting a sport & skill in the Edit Profile
=> Feature/issue 37/add sport and skills

ClientApp/app/editProfile/index.tsx
Fixed the issue where the gender Picker dropdown was cut off on iOS devices.
=> GH-297: [fix] fixed the iOS picker

.github/staged-workflows/release-ci-cd.yml, .github/workflows/ci-cd-controller.yml, .github/workflows/email-service-ci-cd.yml, .github/workflows/event-service-ci-cd.yml, .github/workflows/frontend-ci-cd.yml, .github/workflows/gateway-service-ci-cd.yml, .github/workflows/user-service-ci-cd.yml, ClientApp/package.json, Microservices/email-service/build.gradle, Microservices/event-service/build.gradle, Microservices/user-service/build.gradle
This PR implements the integration of SonarQube into the project to enable continuous static code analysis and ensure adherence to coding standards. It also refactors the CI/CD pipelines across all microservices to include SonarQube analysis, generate test reports, and enforce quality gates based on project standards.
Key changes include:
- Configured **SonarQube** with project-specific quality gates and rules for static code analysis.
- Updated the **CI/CD pipelines** for all microservices and frontend to:
- Run tests and generate coverage reports using **JaCoCo**.
- Integrate with **SonarCloud** for static code analysis.
- Enforce a minimum code coverage threshold of **80%**.
- Added a **release-ci-cd** workflow to ensure releases meet quality and coverage requirements.
- Introduced a …
=> GH-212:  [refactor] Integrate SonarQube and Refactor CI/CD Pipelines for Code Quality Analysis

.github/workflows/email-service-ci-cd.yml, .github/workflows/event-service-ci-cd.yml, .github/workflows/frontend-ci-cd.yml, .github/workflows/gateway-service-ci-cd.yml, .github/workflows/user-service-ci-cd.yml
This PR is meant to fix problems faced while testing new github workflows.
=> GH-0: [fix] Fix GitHub Access Token Permission Issue

.github/workflows/ci-cd-controller.yml
This PR is a quick workflow permission fix.
=> GH-212: [fix] Fix Permission issue in CI/CD Controller

Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/UserProfileResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/controller/UserControllerTest.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserSearchTest.java
This PR aims to refactor /user/search endpoint by adding the userId associated with the profile in the response to establish uniqueness among profiles. 
- UserController.java
- UserService
- UserServiceImpl
- UserProfileResponse
- UserControlellerTest
- UserSearchTest
=> GH-0 : [refactor] Add userId to search endpoint response

Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserSearchTest.java
This PR is a quick refactor of `api/user/search` to return the correct user identifier.
=> GH-0: [refactor] Return Correct Response In User Search Endpoint.

ClientApp/__tests__/createEvent.test.tsx, ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/auth/login.tsx, ClientApp/app/auth/registerAccount.tsx, ClientApp/app/auth/registerProfile.tsx, ClientApp/components/Helper Components/CustomDateTimePicker.tsx, ClientApp/components/Helper Components/EventLocationMap.tsx, ClientApp/components/Helper Components/GooglePlacesInput.tsx, ClientApp/package.json, ClientApp/services/eventService.ts
---
Changes:
- Created a custom iOS and Android date-time picker component.
- Refactored the UI for create event component.
- Improved location map UX.
- Fixed form validation logic.
- Commented out failing tests.
- Fixed minor UI bugs in login & register components.
=> Task/issue 278/android ios date time component

ClientApp/app/(tabs)/profile/(settings)/_layout.tsx, ClientApp/app/(tabs)/profile/(settings)/deleteAccountPage.tsx, ClientApp/app/(tabs)/profile/(settings)/settingsPage.tsx, ClientApp/services/authService.ts
-The "Delete Account" button in the settings redirects to a confirmation screen where the user can proceed or cancel.
-Both the UI and functionality work as expected.
=> GH-276: [feat] User can now delete the account

ClientApp/app/(tabs)/profile/index.tsx, ClientApp/components/Helper Components/FriendCard.tsx, ClientApp/components/Profile/FriendCardProfilePage.tsx, ClientApp/components/Profile/FriendsList.tsx, ClientApp/services/userService.ts, ClientApp/utils/api/endpoints.tsx
now the user can see their friends' list on their own profile page and navigate to their profile page from the list
to test the branch you must have access to two accounts. since sending/accepting requests doesn't have UI yet, you need to do it over swagger. 
or login with my own accounts 
joud.babik@gmail.com
123qweasdzxc
=> GH-291: [feat] Create the friends list on the profile page

ClientApp/__tests__/utils/api/eventApiClient.test.ts, ClientApp/app/events/[eventId].tsx, ClientApp/utils/api/eventApiClient.ts
User can now navigate to other participants user profile from event page.
=> Feature/issue 342/browse participants profile events

ClientApp/app/events/[eventId].tsx, ClientApp/components/Event/EventCard.tsx, ClientApp/utils/mappers/eventIconsMappers.ts
related to #332 and #331: 
for #332 I wasn't able to duplicate the bug so I will retry later or (remove it from the board for now)
for #331 I created a map for the proper names of sports that gets imported.
=> GH-332: [fix] Updated logos for sports on event page

ClientApp/__tests__/components/FriendRequestNotification.test.tsx, ClientApp/__tests__/notifications/notificationPage.test.tsx, ClientApp/__tests__/state/notifications/notificationSlice.test.ts, ClientApp/app/(tabs)/home/(notifications)/_layout.tsx, ClientApp/app/(tabs)/home/(notifications)/friendRequestsPage.tsx, ClientApp/app/(tabs)/home/(notifications)/notificationsPage.tsx, ClientApp/app/(tabs)/home/(notifications)/whatIsNewPage.tsx, ClientApp/app/(tabs)/home/_layout.tsx, ClientApp/components/Helper Components/FriendRequestNotification.tsx, ClientApp/components/Home Page/TopBar.tsx, ClientApp/components/Profile/FriendCardProfilePage.tsx, ClientApp/state/notifications/notificationSlice.ts, ClientApp/state/store.ts, ClientApp/utils/api/endpoints.tsx, ClientApp/utils/api/profileApiClient.ts
- Added foundation functionality of notifications.
- User can now receive friend requests as notifications.
- User can accept friend request from notification.
- User can decline friend request from notification.
- User can visit the user profile of other users from notifications.
- Built layout and UI of notifications.
Notification will be enhanced fully when notification microservice will be ready.
=> Feature/issue 330/notification UI and friend requests

Microservices/event-service/src/test/java/app/sportahub/eventservice/service/social/PostServiceImplTest.java
This pull request addresses the failing tests in  the `PostServiceImplTest` class.
=> GH-0: [test] Fix failing test for post service

ClientApp/app/events/_layout.tsx, ClientApp/package.json, ClientApp/services/eventService.ts
Added event deletion functionality allowing creators to permanently remove their events
=> GH-336: [feat] Restrict event deletion to event creators only

ClientApp/app/editProfile/sportsSkills.tsx, ClientApp/components/RegisterProfile/RegisterProfileSports.tsx
Fixed the color selection bug on the registration profile page. Now, the selected sports retain their assigned colors correctly.
=> GH-359: [fix] Color selection bug on registration page

ClientApp/app.json, ClientApp/package.json
update the app.json to include the new owner of the built project (sportaapp) to share build privileges.
=> update the app.json with owner and location

.github/workflows/build-deploy-microservices.yaml
Brought back the build-args for JAR_FILE in the deployment workflow which was removed on my previous PR.
=> [feat] Add build-args for JAR_FILE in Dockerfile deployment configuration

Microservices/messaging-service/Dockerfile, Microservices/messaging-service/build.gradle, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/config/SecurityConfig.java
This hotfix introduces the actuator to the messaging service like for any of the other MS.
- Added `HEALTHCECK` to the dockerfille.
- Added the actuator dependency to the project.
=> [hotfix] Add Spring Boot Actuator for enhanced application monitoring

.github/workflows/ci-cd-controller.yml, .github/workflows/messaging-service-ci-cd.yml, .github/workflows/orchestration-service-ci-cd.yml, .github/workflows/storage-service-ci-cd.yml
1. Added three new GitHub Actions workflows for the Orchestration Service, Storage Service, and Messaging Service.
2. Integrated the new workflows into the existing controller workflow to ensure they are triggered appropriately.
3. Created corresponding Sonar projects and github secrets for each microservice to be tracked individually.  
4. Ensured consistency and maintainability across all workflows.
=> GH-0 : [refactor] Create Workflows For New Microservices

ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/_layout.tsx, ClientApp/app/auth/login.tsx, ClientApp/app/auth/registerAccount.tsx, ClientApp/app/events/_layout.tsx
1. Fix event page menu (when the ":" is pressed once and twice)
2. Fix going back to login screen swipe back
3. Fix timing on create event
4. Remove OAuth icons from login page and adjust styling for both login and register pages accordingly
=> Bug/issue 385/fix bugs across sporta

ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/events/[eventId].tsx, ClientApp/components/Event/EventCard.tsx, ClientApp/package.json
This PR has the following:
- Added more characters to be allowed on the event name upon creation.
- Styled the text of time left of registration depending on how much time left. Less that a day --> red, green otherwise.
- Fixed the bug where the user is presented with a 403 page when joining an event that its cutoff time has already passed.
- Fixed the cutoff time bug. It was wrongfully calculated before, and thus, we were displaying wrong info as well.
=> handling join of expired event and cutoff time fix

ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/events/[eventId].tsx, ClientApp/components/Helper Components/ClosedButtonEventPage.tsx
This PR handles the use case where a user wants to join an event that the cutoff time has already passed.
=> GH-416: [fix] Join expired event

ClientApp/app/events/[eventId].tsx, ClientApp/utils/localization/en.json, ClientApp/utils/localization/fr.json
This PR includes a single commit for the event page. I forgot to include this commit in my previous PR.
=> GH-399: [fix] Refactor text components for events\[eventId].tsx

Microservices/event-service/src/main/java/app/sportahub/eventservice/utils/KeycloakJwtAuthenticationConverter.java
messed up event service by mistake.
=> GH-0: [hotfix] Accidentally modified event service by mistake

Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/controller/MessagingRESTController.java, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/dto/request/chatroom/ChatroomRequest.java, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/dto/response/chatroom/ChatroomResponse.java, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/exception/ChatroomCreatorMustBeAMemberException.java, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/model/Chatroom.java, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/model/Member.java, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/repository/ChatroomRepository.java, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/service/MessagingService.java, Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/service/MessagingServiceImpl.java, Microservices/messaging-service/src/test/java/app/sportahub/messaging_service/service/MessagingServiceTest.java
created new Member object to be able to store user's usernames.
Chatroom now holds a Set<Member> members instead of a Set<String> members
Implemented dynamic chatroom name for 1 on 1 chatrooms.
=> Hotfix/no ref/messaging service hotfix

Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java
- Removed friend permission requirements to view other users' friend list 
- Part 1 of 2
=> GH-358: [feat] Friend list permission

Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/event/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/request/event/WhitelistRequest.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/NoUserIdsProvidedException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/controller/event/EventControllerTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
This PR is to add the endpoint used for adding user to an events whitelist.
=> Add users to private event whitelist

Microservices/user-service/src/test/java/app/sportahub/userservice/controller/user/UserControllerTest.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
This PR aims to fix the failing test suites:
- `UserControllerTest.java`
- `UserServiceTest.java`
This is done by adding a missing dependency and modifying a User object creation mistake.
=> GH-0: [refactor]  Fix Failing Test Suites

Microservices/orchestration-service/src/main/java/app/sportahub/orchestrationservice/service/consumer/UserServiceConsumerImpl.java, Microservices/orchestration-service/src/test/java/app/sportahub/orchestrationservice/kafka/consumer/UserServiceConsumerTest.java
Fixed orchestration-service test and removed one empty line to trigger the service.
=> [GH-452]: (fix) fix orchestration-service test

ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/(tabs)/home/searchPage.tsx, ClientApp/app/(tabs)/profile/index.tsx, ClientApp/components/Event/EventList.tsx, ClientApp/components/Home Page/HomePageFeed.tsx, ClientApp/package.json, ClientApp/services/eventService.ts
- Fix for search not to rerender as many times when searching
- Add latitude and longitude to the query params being set to filter search
- set getAllRelevantEvents as base for initial events with base distance to 50km
=> GH-432: [bug] Fix search events to not rerender

ClientApp/app/events/[eventId].tsx, ClientApp/app/posts/[id].tsx, ClientApp/components/Event/EventPostsTab.tsx, ClientApp/components/Posts/ImageGridComponent.tsx, ClientApp/components/Posts/PostComponent.tsx, ClientApp/components/Posts/PostCreationComponent.tsx, ClientApp/package.json, ClientApp/services/axiosInstance.ts, ClientApp/utils/api/endpoints.tsx, ClientApp/utils/api/postApiClient.ts, ClientApp/utils/localization/en.json, ClientApp/utils/localization/fr.json
This PR contains the following:
- Implement image upload when creating a post.
- Implement post fetching with images.
- Implement a component to display numerous images dynamically.
- Implement an image viewer when a user clicks on an event.
- Implement dedicated post page.
- Implement fallback in case post does not load or images do not load.
References:
=> Feature/issue 438/post page and image upload

Microservices/event-service/build.gradle, Microservices/notification-service/build.gradle, Microservices/orchestration-service/build.gradle, Microservices/user-service/build.gradle, libs/kafka-events/build.gradle
=> GH-382: [fix] Update kafka-events dependency version to 1.0.8

.helm/event-service-chart/values.yaml, .helm/notification-service-chart/values.yaml, .helm/storage-service-chart/values.yaml, .helm/user-service-chart/values.yaml, ClientApp/app/(tabs)/_layout.tsx, ClientApp/app/auth/login.tsx, ClientApp/services/notificationService.ts, ClientApp/utils/api/endpoints.tsx
This PR introduces push notification support in the client app by implementing device registration and integrating the notification service. Users who log in will now have their device tokens registered, enabling them to receive push notifications.
=> GH-382: [feat] Implement Notification Client App

Microservices/email-service/build.gradle, Microservices/event-service/build.gradle, Microservices/notification-service/build.gradle, Microservices/orchestration-service/build.gradle, Microservices/user-service/build.gradle
This PR if to update the build.gradle file in all microservices that use Kafka-event package. 
Updated version from 1.0.8 to 1.0.9
=> GH-0: [fix] updated kafka events library version to 1.0.9
