Microservices/user-service/src/main/java/app/sportahub/userservice/client/KeycloakApiClient.java, Microservices/user-service/src/main/java/app/sportahub/userservice/controller/auth/AuthController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/auth/SendVerificationEmailRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/auth/AuthService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/auth/AuthServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/controller/AuthControllerTest.java
This PR adds functionality for sending verification email to users to confirm their email. It includes an endpoint, services to use the keycloakapiclient for email sending. Unit tests for the controller are provided to ensure functionality. 
- **Controller**: Added endpoints to assign badges (`PUT /auth/send-verification-email`) 
- **Services**: Added logic for using the Keycloak client to send the verification email
- **Client**: Added method for calling the keycloak endpoint for sending verification email. 
- **Tests**: Added unit tests for the controller/endpoint method.
=> GH-153: [feature] Create resend verification email endpoint

Microservices/user-service/src/main/java/app/sportahub/userservice/client/KeycloakApiClient.java, Microservices/user-service/src/main/java/app/sportahub/userservice/config/auth/SecurityConfig.java, Microservices/user-service/src/main/java/app/sportahub/userservice/controller/auth/AuthController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/auth/SendPasswordResetEmailRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/GlobalExceptionHandler.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/auth/AuthService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/auth/AuthServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/controller/AuthControllerTest.java
This pull request focuses on the creation of password-reset endpoint to allow a user to change their lost, forgotten, or compromised password. Modifications include sending password reset email with a time-limited link, updating user credentials, and conducting unit tests to make sure the endpoint functions as expected.
- `SendPasswordResetEmailRequest.java`: Cretae DTO to capture user email in http request
- `KeycloakApiClient.java` : Add new method to handle sending and receiving http response
- `AuthController.java`: Add new endpoint
- `GlobalExceptionHandler.java`: Add UserWithEmailDoesNotExist exception
- `AuthService.java`: Add sendPasswordResetEmail method
- `AuthServiceImpl.java`: Implement sendPasswordResetEmail method
- `AuthControllerTest.java`: Add new test cases for reset …
=> GH-101: [feat] password reset endpoint

Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/user/FriendRequestRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/user/UserRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/FriendRequestResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/UserResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/enums/user/FriendRequestStatusEnum.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/GlobalExceptionHandler.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/UserAlreadyInFriendListException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/UserAlreadyInFriendListException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/UserDoesNotExistException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/UserSentFriendRequestToSelfException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/UserWithEmailDoesNotExistException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/model/user/Friend.java, Microservices/user-service/src/main/java/app/sportahub/userservice/model/user/User.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/controller/AuthControllerTest.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
Created a new endpoint /user/{userId}/friends/requests to send friend requests to other users.
The sendFrindRequest method inside UserServiceImpl verifies the following:
- that the sender and receiver are existing users
- that the sender hasn't sent a friend request to this user already
- that the sender hasn't sent a friend request to themselves
A new Friend object was created to keep track of friends. It contains String username and FriendRequestStatusEnum status.
The User model was modified to include an Array List of Type Friend.
The FriendRequestStatusEnum has 3 possible values: "SENT", "RECEIVED", and "ACCEPTED"
When the sendFriendRequest method executes successfully, a friend is added to the friend list of both the sender and receiver with appropriate information.
=> GH-190: Send friend request

ClientApp/__tests__/profile.test.tsx, ClientApp/app/(tabs)/profile/index.tsx, ClientApp/package.json, ClientApp/utils/api/profileApiClient.ts, ClientApp/utils/helpers/ageOfUser.ts
fix for #205 Before the profile page was using a json server awaiting the major infrastructure changes that were recently updated
the page would show defaulted values for the fields instead of the user information as per image below
the console would receive error due to the wrong endpoint 
After the fix: 
The profile page shows the logged user information from the backend
=> GH-205: bug fix for profile page information fetch

ClientApp/jest.setup.ts, ClientApp/package.json
Failing frontend CI test because of the SDK migration.
The following solution includes the proper modifications to the package.json and jest.setup.ts
=> GH-220:[fix] FIx CI failing test

Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/friend/FriendRequestResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/friend/ViewFriendRequestsResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/GlobalExceptionHandler.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/friend/InvalidFriendRequestStatusTypeException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/friend/UserAlreadyInFriendListException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/friend/UserSentFriendRequestToSelfException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
This PR is for the /user/{userId}/friend-requests endpoint which returns a list of received friend requests for the user with the corresponding userId.
The user service method goes through the user's friend list and filters out every friend whose status is not "RECEIVED", then returns this list as a List<ViewFriendRequestsResponse> object that contains all usernames of the users who sent a friend request.
the user service method throws a UserDoesNotExistException if the given userId does not correspond to a valid user.
=> GH-209: [feature] Created endpoint for viewing received friend requests.

Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/user/friend/FriendRequestRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/request/user/friend/UpdateFriendRequestRequest.java, Microservices/user-service/src/main/java/app/sportahub/userservice/dto/response/user/friend/UpdateFriendRequestResponse.java, Microservices/user-service/src/main/java/app/sportahub/userservice/enums/user/UpdateFriendRequestActionEnum.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/GlobalExceptionHandler.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/friend/FriendDoesNotExistException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/friend/FriendNotFoundInFriendListException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/friend/GivenFriendUsernameDoesNotMatchFriendFoundByIdException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/friend/TryingToAcceptInvalidFriendRequestException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/exception/user/friend/UnexpectedUpdateFriendRequestActionException.java, Microservices/user-service/src/main/java/app/sportahub/userservice/model/user/Friend.java, Microservices/user-service/src/main/java/app/sportahub/userservice/repository/FriendRepository.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
This PR implements an endpoint to accept or decline friend requests.
It also refactors the Friend object to now hold an id.
The userService.updateFriendRequest method takes in a given userId, requestId, and an UpdateFriendRequestRequest consisting of the username of the friend whose request you want to modify, as well as an action represented by an enum with two possible inputs; ACCEPT or DECLINE.
It checks if the inputs are valid and updates the affected users' friendlists by either modifying the status in the case of an ACCEPT action, or removing the friend from the friendlist if the given action is DECLINE.
Unit tests were written to validate successful and unsuccessful calls to the method.
=> GH-210: [feature] Created an endpoint to Accept or Decline friend requests

Microservices/event-service/src/main/java/app/sportahub/eventservice/config/WebConfig.java, Microservices/user-service/src/main/java/app/sportahub/userservice/config/auth/WebConfig.java
This pull request addresses issue #225 by updating the CORS configuration in both `event-service` and `user-service` to include support for PATCH and HEAD methods. Previously, these methods were not allowed in Swagger, though they worked correctly in Postman.
**Changes Made:**  
- Updated the `allowedMethods` in `WebConfig.java` to include `"PATCH"` and `"HEAD"`.  
- Adjusted CORS policies for both `event-service` and `user-service` to enable seamless testing and execution of these methods via Swagger UI.
**Closing Keywords:**  
This PR closes #225.
---
1. Verified the updated CORS configuration by running the services locally.  
2. Successfully executed PATCH and HEAD operations through Swagger UI.  
3. Cross-verified the operations' functionality in Postman to ensure consistency.  
--- …
=> GH-225: [fix] Allow patch and head operations through Swagger

Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/response/EventResponse.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/response/ParticipantResponse.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/mapper/event/EventMapper.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
This pull request resolves an issue where the `participantAttendStatus` field was not being correctly set when a user joined an event. The following changes have been made:
- Added a `ParticipantResponse` DTO to include `participantAttendStatus`, `userId`, and `joinedOn`.
- Updated the `joinEvent` method to return a `ParticipantResponse` after successfully adding the participant.
- Refactored the `EventService` and its implementation to handle the assignment of the default `participantAttendStatus`.
- Adjusted the mapper to include the new `ParticipantResponse` structure.
- Added a default status for new participants.
- Updated `EventService` interface and implementation.
- Modified `joinEvent` in `EventController` to return the participant response.
- Added a new DTO …
=> GH-232: [fix] Assign default participantAttendStatus when a player joins an event

ClientApp/app/(tabs)/profile/index.tsx, ClientApp/components/Event/EventCard.tsx, ClientApp/components/Event/EventListProfilePage.tsx, ClientApp/components/Event/EventsListHomePage.tsx, ClientApp/components/Home Page/Feed.tsx
for #202 create event card on the profile page with limited information as a summary of the events that the user have participated in 
the card on the profile page has limited information compared to the one one on the homepage. they are ordered from upcoming to past, with the cards for events that expired (happened) in darker color.
=> GH-202: Feature/issue 202/create event card on profile page of user

Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserService.java, Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
**Description:**  
This PR introduces the ability to delete users by their unique identifier. The following changes were made:  
- Added a new `DELETE user/{id}` endpoint in `UserController`.  
- Implemented `deleteUserById` method in `UserService` and `UserServiceImpl`.  
- Included error handling for cases where the user does not exist or when the Keycloak deletion fails.  
- Added unit tests to cover successful deletion, user not found, and Keycloak communication errors.  
Closes GH-208.
=> GH-208: [feat] Added functionality to delete users

ClientApp/app/events/[eventId].tsx
Related issue: #292 
When the user joins an event now, he will be able to see his avatar added automatically in the participants list. This removes the confusion of either the user is enrolled or not. It also gives a better user experience since he does not need to go back and lick again on the event to confirm that he is actually enrolled.
=> GH-292: [fix] Fix participant list update

Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/EventController.java
This PR is for a quick bug fix. 
There was a typo in the `EventController` endpoint `event/participant/{userId}`. It was previously written `event/patricipant/{userId}`.
=> GH-0: [fix] fixed type in endpoint for retrieving events participated in by a user

.github/workflows/build-deploy-microservices.yaml
This pull request addresses and resolves the issue with the microservice Docker image failing to run due to an "Invalid or corrupt jarfile" error.
- Updated the GitHub Actions workflow to correctly determine the JAR file to be used in the Docker image.
- The script now correctly excludes the "plain" JAR files, ensuring that the Docker image contains the appropriate JAR.
- Added build argument in the Docker build step to pass the correct JAR file path.
This fix ensures that the microservice Docker images are built with valid JAR files and can run successfully without errors.
Closes #317
- Verified the workflow runs successfully and the correct JAR file is identified and included in the Docker image.
- Tested running the Docker image locally to ensure no runtime errors occur.
=> GH-317: [fix] Fix Microservice Image Build

Microservices/storage-service/build.gradle
Hot fix to change jdk version from Java 17 to Java 21 for storage service
=> GH-0: [chore] Changing jdk version to Java 21 for storage service

Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/EventAlreadyStartedException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/EventCreatorCannotLeaveEvent.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/EventCreatorCannotLeaveEventException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/UserNotAParticipantException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/model/event/participant/ParticipantAttendStatus.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/controller/EventControllerTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
This pull request focuses on the creation of `event/{id}/leave` endpoint to allow users to leave an event, provided they are not the creator and has not started.
- EventController.java: Add new endpoint
- EventAlreadyStartedException.java: Add EventAlreadyStartedException exception 
- EventCreatorCannotLeaveException.java: Add EventCreatorCannotLeaveException exception 
- UserNotAParticipantException.java: Add UserNotAParticipantException exception 
- EventService.java: Add leaveEvent method
- EventServiceImpl.java: Implement leaveEvent method
- EventControllerTest.java Add new test cases for leave endpoint
- EventServiceTest.java Add new test cases for leave service logic
- Successfully send request ✔️
- Throw exception if creators tries to leave their event✔️
- Throw exception if user …
=> GH-320: [feat] Implement Leave Event Endpoint

Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/request/EventCancellationRequest.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/response/EventResponse.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/enums/EventState.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/EventAlreadyCancelledException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/model/event/Event.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/model/event/EventCancellation.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/controller/EventControllerTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/mapper/event/EventMapperTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
This PR introduces the **event cancellation feature**, allowing events to be marked as `CANCELLED` instead of being deleted. The following changes have been implemented:
1. **Added `EventState` Enum**:
- Defines the possible states for an event: `ACTIVE` and `CANCELLED`.
2. **Introduced `EventCancellation` Model**:
- Stores cancellation metadata (`cancelledBy`, `reason`, `cancelledAt`).
- Embedded within the `Event` model to track cancellations directly.
3. **Implemented `cancelEvent` API Endpoint**:
- Added a new `PATCH /event/{id}/cancel` endpoint.
- Only the **event creator** or **admin** can cancel events.
- Requires a reason for cancellation.
4. **Modified `EventResponse` to Include `EventCancellation`**:
- Updated DTO to return cancellation details.
5. **Added Exception Handling**: …
=> GH-335: [feat] Add Event state enums & Event Cancellation model

Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
This PR aims to fix test failure and also update mistake in recently merged branch, namely the following:
The correct logic of leaveEvent feature is to throw EventAlreadyStartedException when the a participant is trying to leave after the event's start _time_, not event's start _date_.
=> GH-0: [feat] Fix Failing Test and Update leaveEvent Logic

Microservices/event-service/src/main/java/app/sportahub/eventservice/config/MongoConfig.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/event/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/request/event/LocationRequest.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/response/LocationResponse.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/EventsNotFoundException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/model/event/Location.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/repository/event/EventRepository.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/main/resources/application.properties, Microservices/event-service/src/test/java/app/sportahub/eventservice/controller/event/EventControllerTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/mapper/event/EventMapperTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
This PR is for issue #334 which introduces browsing events that are in your proximity. 
- `EventController`: Added endpoint `event/relevant-events` to retrieve the relevant events and has the following request parameters : 
>- `longitude` : a double for the longitude of the users location 
>- `latitude`: a double for the latitude of the users location 
>- `radius`: a double for the search radius of events 
>- `radiusExpansion`: a **Boolean** indicating whether or not to expand the search radius if no events found in given radius
>- `paginate`: a **Boolean** indicating whether or not the returned results are paginated 
>- `page`: an **Integer** indicating the page for paginated response 
>- `size`: an **Integer** indicating the size of each page for paginated response 
- `UserServiceImpl` …
=> Get Events That Matches The User's Profile For Their Home Page Browsing

ClientApp/app/(tabs)/create/index.tsx, ClientApp/app/(tabs)/home/searchPage.tsx, ClientApp/app/events/[eventId].tsx, ClientApp/components/Helper Components/GooglePlacesInput.tsx, ClientApp/types/event.ts, ClientApp/utils/api/eventApiClient.ts
This PR includes all the UI for search events without any search functionality until implemented later.
- Add map view of events when searching for events.
- Add list view of events (reused component).
- Add toggle button between map view and list view.
- Match updates in the event model that were made in #366.
1. Login
2. Allow location access (ensure it's enabled in the simulator)
3. Press on the search icon located top right on the header of home page
4. Toggle "Events" tab
- Montreal Tech Conference1
- Montreal Tech Conference3
- Montreal Tech Conference4
- Youssef march6 test5
- Can you toggle between list view and map view without issues?
- Does list view contain events?
- Does map view contain events?
- Does map view show markers for event locations?
- When pressing on an event, do …
=> Feature/issue 373/events map view

ClientApp/components/QR/QR.tsx, ClientApp/services/eventService.ts
- Fix for the QR code displaying cannot have react.children inside bottomModal
- Implements the event filtering upon date functionality in the frontend
Test:
- For QR, simply go to profile or event and press on display QR code to share either event/profile and modal should appear with no error
- For filtering, select any two dates between a date range and see the events appear accordingly
=> GH-386: [bug] Fixes for QR UI and event service filtering

ClientApp/app.json
The app now has a unique splash screen and logo displayed that users can see. The user is now able to locate the app easier. Also when opened, the app displayed its splash screen enhancing the credibility of the team and app.
Refrences:
=> GH-388: [feat] implement app splash screen and logo

ClientApp/app/events/[eventId].tsx, ClientApp/components/Event/EventPostsTab.tsx
- Post creation option is now restricted for only joined users of an event.
- Not all users will see the create post option.
- Small UI improvement to display different fallback messages where there are no posts to display or when the user has reached the end when displaying posts.
References:
=> GH-390: [fix] restrict post creation to only joined users and UI improvement

Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java, Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
The getFriends endpoint was returning 404 when trying to return users no longer in the database. Now it will remove them from the friendList and delete them before returning if they can't be found in the database.
This led me to realize that friends could only be deleted if they appeared in both friendLists (Requester and Friend), which shouldn't have been the case.  That's also fixed.
Also, friend requests could be sent to users already accepted into the friendList, now there's a check preventing that in the sendFriendRequest method.
1. You need two valid user accouts (one of which you'll delete)
2. Run the user-service locally
3. Using Swagger/Postman, log into one of the users and add the other as a friend
4. Delete the user you just added as a friend
5. Call the get friends endpoint, …
=> [hotfix] 404 getFriends issue

ClientApp/utils/api/endpoints.tsx, ClientApp/utils/api/profileApiClient.ts
The logged in user can now see the posts that other people have made in any event page.
=> GH-403: [fix] Posts display access error fix

ClientApp/app.json, ClientApp/components/Posts/PostCreationComponent.tsx, ClientApp/package.json
Fixed the iPhone camera issue when posting an event by adding proper camera permissions and updating expo-image-picker API usage. Tested on iOS to ensure the camera opens and attaches images correctly.
=> GH-408: [Bug] Fixed iPhone camera issue when posting an event

ClientApp/app/events/[eventId].tsx, ClientApp/app/events/_layout.tsx, ClientApp/services/eventService.ts, ClientApp/types/event.ts, ClientApp/utils/api/endpoints.tsx
Added the ability for users to leave an event they previously joined.
A confirmation message is displayed upon successfully leaving an event.
In some cases, leaving an event fails with a 500 error due to a backend issue.
Some events might have a deadline restriction preventing users from leaving.
=> Gh-410: [feat] Implement leave event functionality

.gitignore, Microservices/storage-service/src/main/resources/application.properties
This PR increases the file upload size limit in the Storage Service to **10GB** to allow larger file uploads.  
- Updated `application.properties` in `storage-service` to set:  
- `spring.servlet.multipart.max-file-size=10GB`  
- `spring.servlet.multipart.max-request-size=10GB`  
- Updated `.gitignore` to include additional IDE and build-related files.  
Closes #430  
- Verified that file uploads up to 10GB are processed without errors.  
- Ensured that smaller file uploads continue to function correctly.  
- Checked that the changes do not impact other microservices.  
- Enables users to upload larger files without hitting the previous limit.  
- No expected regressions, as the limits are now configurable.
=> [BUG] Storage Service Size Limit Too Low

ClientApp/app/events/[eventId].tsx, ClientApp/app/events/_layout.tsx, ClientApp/components/Event/EventCard.tsx, ClientApp/services/eventService.ts, ClientApp/types/event.ts, ClientApp/utils/api/endpoints.tsx
Integrated event cancellation functionality:
- Creators can now cancel events with a reason.
- Cancelled events are marked as (Cancelled) in both the event page and homepage feed.
- Removed cancellation reason display from the UI for better UX.
=> Feat/issue 413/cancel event

Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/event/EventController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/InvalidEventCoordinatesReceivedException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/controller/event/EventControllerTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventSearchTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
Added distance filter that mimics the logic of the GET relevant-events endpoint; start at a radius of 25km and double if no events are found.
Also added a check to the create event method that enforces proper GeoJsonPoint coordinates before creating the event, as this was causing issues with returning search results.
As a safety, I also added a check that will ignore all events with invalid GeoJsonPoints from search results, preventing the search event method from throwing an error if it encounters such events.
Fixed all tests that broke due to these changes.
=> GH-0: [refactor] Added distance filter to event search endpoint.

Microservices/event-service/src/main/java/app/sportahub/eventservice/config/kafka/KafkaProducerConfig.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/social/PostController.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/request/social/CommentRequest.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/response/social/CommentResponse.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/response/social/PostResponse.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/CommentDoesNotExistException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/PostDoesNotExistException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/ReactionAlreadySubmittedException.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/mapper/social/CommentMapper.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/mapper/social/PostMapper.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/model/social/Post.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/repository/social/CommentRepository.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/social/PostService.java, Microservices/event-service/src/main/java/app/sportahub/eventservice/service/social/PostServiceImpl.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/controller/social/PostControllerTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventSearchTest.java, Microservices/event-service/src/test/java/app/sportahub/eventservice/service/social/PostServiceImplTest.java
This PR aims at introducing the following endpoints to interact with event posts and comments:
- GET `event/{eventId}/social/post/{postID}` to retrieve a specific Post with its comments.
- DELETE `event/{eventId}/social/post/{postID}` to delete the Post associated with the postId and eventId provided.
- POST `event/{eventId}/social/post/{postID}/comment` to create a Comment under the specified Post.
- DELETE `event/{eventId}/social/post/{postID}/comment/{commentId}` to delete a Comment in the Post specified.
- POST `event/{eventId}/social/post/{postID}/reaction` to allow users to react to a Post in an Event.
Tested controller and service layer logic to ensure desired behavior is acheived.
=> GH-0: [feat] Creat Endpoints For Posts in Events

Microservices/notification-service/src/main/java/app/sportahub/notificationservice/config/auth/SecurityConfig.java
Notification Service is failing because it is not allowing health checks.
=> [fix] Update SecurityConfig to allow access to actuator endpoints

Microservices/event-service/src/main/java/app/sportahub/eventservice/config/kafka/KafkaProducerConfig.java
This PR removes a redundant `kafkaTemplate` bean method in `KafkaProducerConfig`. The method was unnecessary as there was already a properly defined `KafkaTemplate` bean that uses `ProducerFactory`. It causes the app to crash.
=> [fix] Remove Redundant KafkaTemplate Bean Method

README.md
Removing unnecessary parts, and adding more of a structure to it.
=> Improving readme structure 
